#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

function usage() {
  console.log('Usage: node scripts/confidence-score.js <workspace-dir>');
  console.log('The workspace should contain docs/output/ files generated by product-requirement-foundry.');
}

function exists(file) {
  return fs.existsSync(file);
}

function readIfExists(file) {
  return exists(file) ? fs.readFileSync(file, 'utf8') : '';
}

function writeJson(file, value) {
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function containsAny(text, patterns) {
  const lower = text.toLowerCase();
  return patterns.some(pattern => lower.includes(pattern.toLowerCase()));
}

function parseMarkdownTables(markdown) {
  const tables = [];
  const lines = markdown.split(/\r?\n/);
  let current = [];

  for (const line of lines) {
    if (/^\s*\|.+\|\s*$/.test(line)) {
      current.push(line.trim());
    } else if (current.length > 0) {
      tables.push(current);
      current = [];
    }
  }
  if (current.length > 0) tables.push(current);

  return tables.map(table => {
    const rows = table
      .filter(line => !/^\|\s*-+/.test(line))
      .map(line => line.split('|').slice(1, -1).map(cell => cell.trim()));
    const [header, ...body] = rows;
    return { header: header || [], rows: body };
  });
}

function tableObjects(markdown) {
  const objects = [];
  for (const table of parseMarkdownTables(markdown)) {
    for (const row of table.rows) {
      const obj = {};
      table.header.forEach((key, index) => {
        obj[key || `Column ${index + 1}`] = row[index] || '';
      });
      objects.push(obj);
    }
  }
  return objects;
}

function firstNonEmpty(...values) {
  return values.find(value => value && String(value).trim()) || '';
}

function buildEvidenceChain(outputDir) {
  const refs = readIfExists(path.join(outputDir, 'baseline-references.md'));
  const prd = readIfExists(path.join(outputDir, 'prd.md'));
  const devContext = readIfExists(path.join(outputDir, 'openspec', 'dev-context.md'));
  const rows = [];

  for (const item of tableObjects(refs)) {
    const sourceType = firstNonEmpty(item['Source type'], item['Source Type'], item.Source);
    const sourceReference = firstNonEmpty(item['Source reference'], item['Source Reference'], item['Historical source'], item['Historical Source']);
    const proof = firstNonEmpty(item['Why it matters'], item['How reused'], item['Impact on this change'], item.Notes);
    const confidence = firstNonEmpty(item.Confidence, item.confidence);
    if (sourceReference || proof) {
      rows.push({
        claim: firstNonEmpty(item.Concept, item.Item, item.Constraint, item['Requirement item'], 'Historical reference'),
        sourceType,
        sourceReference,
        proof,
        compatibility: firstNonEmpty(item['Impact on this change'], item['How reused'], proof),
        confidence: confidence || (sourceType && sourceReference ? 'High' : 'Medium')
      });
    }
  }

  for (const item of tableObjects(prd)) {
    const source = firstNonEmpty(item.Source, item['Source type'], item['Source Type']);
    if (source) {
      rows.push({
        claim: firstNonEmpty(item.Area, item.Item, item['Change description'], item['Requirement item'], 'PRD claim'),
        sourceType: source,
        sourceReference: firstNonEmpty(item['Source reference'], item['Source Reference'], item.Notes),
        proof: firstNonEmpty(item.Current, item.Target, item.Notes),
        compatibility: firstNonEmpty(item['Change type'], item.Target, item.Notes),
        confidence: source.toLowerCase().includes('ai') ? 'Low' : 'Medium'
      });
    }
  }

  for (const item of tableObjects(devContext)) {
    const sourceType = firstNonEmpty(item['Source type'], item['Source Type']);
    const sourceReference = firstNonEmpty(item['Source reference'], item['Source Reference']);
    if (sourceReference || sourceType) {
      rows.push({
        claim: firstNonEmpty(item['Key fact'], item.Item, 'Development context baseline'),
        sourceType,
        sourceReference,
        proof: firstNonEmpty(item['Key fact'], item.Notes),
        compatibility: 'Used as implementation boundary',
        confidence: sourceType && sourceReference ? 'High' : 'Medium'
      });
    }
  }

  const seen = new Set();
  return rows.filter(row => {
    const key = `${row.claim}|${row.sourceReference}|${row.proof}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return row.claim || row.sourceReference || row.proof;
  });
}

function buildCompatibilityProof(outputDir, evidenceChain) {
  const prd = readIfExists(path.join(outputDir, 'prd.md'));
  const impact = readIfExists(path.join(outputDir, 'impact-analysis.md'));
  const design = readIfExists(path.join(outputDir, 'openspec', 'design.md'));
  const devContext = readIfExists(path.join(outputDir, 'openspec', 'dev-context.md'));
  const combined = `${prd}\n${impact}\n${design}\n${devContext}`;
  const proof = [];

  const checks = [
    ['Current online behavior is described', ['current online', 'current behavior', 'Current Online Solution', 'Current Behavior']],
    ['Delta between old and new behavior is described', ['Delta Overview', 'Current | Target', 'current | target', 'change type']],
    ['Compatibility or fallback behavior is described', ['compatibility', 'fallback', 'Backward compatibility']],
    ['Rollback or feature flag strategy is described', ['rollback', 'feature flag', 'Feature Flags']],
    ['Regression or validation scope is described', ['regression', 'Validation Strategy', 'Acceptance']]
  ];

  for (const [claim, patterns] of checks) {
    proof.push({
      claim,
      status: containsAny(combined, patterns) ? 'Proved by artifact text' : 'Missing evidence',
      evidence: patterns.find(pattern => containsAny(combined, [pattern])) || ''
    });
  }

  proof.push({
    claim: 'Historical source references are present',
    status: evidenceChain.length > 0 ? 'Proved by evidence chain' : 'Missing evidence',
    evidence: `${evidenceChain.length} evidence rows`
  });

  return proof;
}

function buildEvidenceGaps(evidenceChain, result) {
  const gaps = [];
  if (evidenceChain.length === 0) {
    gaps.push('No evidence chain rows were extracted from baseline references, PRD, or dev context.');
  }
  const lowConfidence = evidenceChain.filter(item => String(item.confidence).toLowerCase() === 'low');
  if (lowConfidence.length > 0) {
    gaps.push(`${lowConfidence.length} evidence rows are low confidence and need human confirmation.`);
  }
  const incompleteReferences = evidenceChain.filter(item => !item.sourceType || !item.sourceReference);
  if (incompleteReferences.length > 0) {
    gaps.push(`${incompleteReferences.length} evidence rows lack a source type or full source reference.`);
  }
  for (const item of result.breakdown || []) {
    if (item.score < 85 && item.notes.length > 0) {
      gaps.push(`${item.dimension}: ${item.notes.join('; ')}`);
    }
  }
  return gaps;
}

function scoreBaseline(outputDir) {
  let score = 0;
  const notes = [];
  const required = [
    'baseline-summary.md',
    'feature-inventory.json',
    'historical-requirements.json',
    'known-constraints.json'
  ];

  for (const file of required) {
    if (exists(path.join(outputDir, file))) score += 20;
    else notes.push(`Missing ${file}`);
  }

  const baselineRefs = readIfExists(path.join(outputDir, 'baseline-references.md'));
  if (baselineRefs) score += 20;
  else notes.push('Missing baseline-references.md');

  return { score: Math.min(score, 100), notes };
}

function scoreIntent(outputDir) {
  const prd = readIfExists(path.join(outputDir, 'prd.md'));
  const notes = [];
  let score = 0;

  if (prd) score += 20;
  else notes.push('Missing prd.md');

  if (containsAny(prd, ['goal', 'goals', '目标'])) score += 20;
  else notes.push('Goals not detected');

  if (containsAny(prd, ['non-goal', 'non-goals', '非目标'])) score += 20;
  else notes.push('Non-goals not detected');

  if (containsAny(prd, ['scenario', '场景', 'user'])) score += 20;
  else notes.push('User scenario not detected');

  if (containsAny(prd, ['open question', 'open questions', '待确认'])) score += 20;
  else notes.push('Open questions section not detected');

  return { score, notes };
}

function scoreConsistency(outputDir) {
  const prd = readIfExists(path.join(outputDir, 'prd.md'));
  const consistency = readIfExists(path.join(outputDir, 'consistency-review.md'));
  const refs = readIfExists(path.join(outputDir, 'baseline-references.md'));
  const notes = [];
  let score = 0;

  if (containsAny(prd, ['current online', 'current behavior', '当前线上', '当前行为'])) score += 25;
  else notes.push('Current online behavior not detected');

  if (containsAny(prd, ['delta', 'change type', '新增', '修改', '不变'])) score += 25;
  else notes.push('Delta/change description not detected');

  if (refs) score += 25;
  else notes.push('Source traceability not detected');

  if (consistency) score += 25;
  else notes.push('Missing consistency-review.md');

  return { score, notes };
}

function scoreImpact(outputDir) {
  const impact = readIfExists(path.join(outputDir, 'impact-analysis.md'));
  const checklist = readIfExists(path.join(outputDir, 'change-checklist.md'));
  const notes = [];
  let score = 0;

  if (impact) score += 20;
  else notes.push('Missing impact-analysis.md');

  if (containsAny(impact, ['module', '模块'])) score += 15;
  else notes.push('Affected modules not detected');

  if (containsAny(impact, ['page', '页面'])) score += 15;
  else notes.push('Affected pages not detected');

  if (containsAny(impact, ['api', 'interface', '接口'])) score += 15;
  else notes.push('API impact not detected');

  if (containsAny(impact, ['data', 'entity', 'table', '数据'])) score += 15;
  else notes.push('Data impact not detected');

  if (containsAny(impact, ['event', 'tracking', 'metric', '埋点'])) score += 10;
  else notes.push('Tracking impact not detected');

  if (checklist) score += 10;
  else notes.push('Missing change-checklist.md');

  return { score, notes };
}

function scoreOpenSpec(outputDir) {
  const openspecDir = path.join(outputDir, 'openspec');
  const files = ['proposal.md', 'design.md', 'spec.md', 'tasks.md', 'dev-context.md'];
  const notes = [];
  let score = 0;

  for (const file of files) {
    if (exists(path.join(openspecDir, file))) score += 15;
    else notes.push(`Missing openspec/${file}`);
  }

  const spec = readIfExists(path.join(openspecDir, 'spec.md'));
  if (containsAny(spec, ['given', 'when', 'then', 'scenario'])) score += 15;
  else notes.push('OpenSpec scenarios not detected');

  const tasks = readIfExists(path.join(openspecDir, 'tasks.md'));
  if (containsAny(tasks, ['- [ ]'])) score += 10;
  else notes.push('Executable task checklist not detected');

  return { score: Math.min(score, 100), notes };
}

function status(score, blockingIssues) {
  if (blockingIssues.length > 0 || score < 60) return 'Blocked';
  if (score < 85) return 'Review Required';
  return 'Pass';
}

function renderMarkdown(result) {
  const lines = [];
  lines.push('# Confidence Report');
  lines.push('');
  lines.push('## Overall Score');
  lines.push('');
  lines.push(`- Total: ${result.total} / 100`);
  lines.push(`- Status: ${result.status}`);
  lines.push('');
  lines.push('## Score Breakdown');
  lines.push('');
  lines.push('| Dimension | Score | Status | Notes |');
  lines.push('|---|---:|---|---|');
  for (const item of result.breakdown) {
    lines.push(`| ${item.dimension} | ${item.score} | ${status(item.score, [])} | ${item.notes.join('; ') || 'No major gaps detected'} |`);
  }
  lines.push('');
  lines.push('## Blocking Issues');
  lines.push('');
  if (result.blockingIssues.length === 0) lines.push('- None detected by automated checks.');
  else result.blockingIssues.forEach(issue => lines.push(`- ${issue}`));
  lines.push('');
  lines.push('## Review Required');
  lines.push('');
  if (result.reviewRequired.length === 0) lines.push('- None detected by automated checks.');
  else result.reviewRequired.forEach(issue => lines.push(`- ${issue}`));
  lines.push('');
  lines.push('## Evidence Chain');
  lines.push('');
  if (result.evidenceChain.length === 0) {
    lines.push('- No evidence rows extracted. Add `baseline-references.md` and source traceability tables.');
  } else {
    lines.push('| Claim | Source type | Source reference | Proof | Compatibility proof | Confidence |');
    lines.push('|---|---|---|---|---|---|');
    for (const item of result.evidenceChain) {
      lines.push(`| ${item.claim} | ${item.sourceType} | ${item.sourceReference} | ${item.proof} | ${item.compatibility} | ${item.confidence} |`);
    }
  }
  lines.push('');
  lines.push('## Compatibility Proof');
  lines.push('');
  lines.push('| Claim | Status | Evidence |');
  lines.push('|---|---|---|');
  for (const item of result.compatibilityProof) {
    lines.push(`| ${item.claim} | ${item.status} | ${item.evidence} |`);
  }
  lines.push('');
  lines.push('## Evidence Gaps');
  lines.push('');
  if (result.evidenceGaps.length === 0) lines.push('- None detected by automated checks.');
  else result.evidenceGaps.forEach(gap => lines.push(`- ${gap}`));
  lines.push('');
  lines.push('## Product Review Checklist');
  lines.push('');
  lines.push('- [ ] Requirement goal is correct');
  lines.push('- [ ] Non-goals are acceptable');
  lines.push('- [ ] Current online behavior is accurate');
  lines.push('- [ ] Delta scope is correct');
  lines.push('- [ ] Open questions are acceptable');
  lines.push('');
  lines.push('## Engineering Review Checklist');
  lines.push('');
  lines.push('- [ ] Affected modules are complete');
  lines.push('- [ ] API impact is accurate');
  lines.push('- [ ] Data impact is accurate');
  lines.push('- [ ] Tracking impact is accurate');
  lines.push('- [ ] Rollout and rollback are feasible');
  lines.push('- [ ] Test scope is complete');
  lines.push('');
  return lines.join('\n');
}

function main() {
  const workspace = path.resolve(process.argv[2] || '.');
  if (process.argv.includes('--help')) {
    usage();
    return 0;
  }

  const outputDir = path.join(workspace, 'docs', 'output');
  if (!exists(outputDir)) {
    console.error(`Missing output directory: ${outputDir}`);
    usage();
    return 1;
  }

  const dimensions = [
    ['Baseline Reliability', scoreBaseline(outputDir)],
    ['Intent Alignment', scoreIntent(outputDir)],
    ['Historical Consistency', scoreConsistency(outputDir)],
    ['Impact Completeness', scoreImpact(outputDir)],
    ['OpenSpec Readiness', scoreOpenSpec(outputDir)]
  ];

  const breakdown = dimensions.map(([dimension, value]) => ({
    dimension,
    score: value.score,
    notes: value.notes
  }));

  const total = Math.round(breakdown.reduce((sum, item) => sum + item.score, 0) / breakdown.length);
  const blockingIssues = [];
  const reviewRequired = [];

  for (const item of breakdown) {
    if (item.score < 60) blockingIssues.push(`${item.dimension}: ${item.notes.join('; ')}`);
    else if (item.score < 85) reviewRequired.push(`${item.dimension}: ${item.notes.join('; ')}`);
  }

  const result = {
    total,
    status: status(total, blockingIssues),
    breakdown,
    blockingIssues,
    reviewRequired,
    evidenceChain: [],
    compatibilityProof: [],
    evidenceGaps: []
  };

  result.evidenceChain = buildEvidenceChain(outputDir);
  result.compatibilityProof = buildCompatibilityProof(outputDir, result.evidenceChain);
  result.evidenceGaps = buildEvidenceGaps(result.evidenceChain, result);
  if (result.evidenceGaps.length > 0 && result.status === 'Pass') {
    result.status = 'Review Required';
    result.reviewRequired.push(...result.evidenceGaps);
  }

  writeJson(path.join(outputDir, 'confidence-score.json'), result);
  fs.writeFileSync(path.join(outputDir, 'confidence-report.md'), renderMarkdown(result), 'utf8');

  console.log(`Confidence score: ${result.total}/100 (${result.status})`);
  console.log(`Wrote confidence report to ${outputDir}`);
  return 0;
}

process.exitCode = main();
